### ISSUE TITLE
Incompatible with Betweenlands 

### ISSUE THREAD

**Issue by Neglevin** [superfluke/somelikeitdry#1]
Whenever I try to enter the Betweenlands dimension with this mod, the world generation is always really messed up. It's just a large ocean that reaches bedrock. Here's a screenshot of it: https://imgur.com/a/eYm43MO

**Comment by superfluke** [comment]
Lol the irony of some like it dry's bug being an entire dim made of oceans. I'll look into it, thanks for the report.
